name: isogram
version: 1.2.0.2

dependencies:
  - base
  - text
library:
  exposed-modules: Isogram
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - isogram
      - hspec
